import Foundation
import Observation
import SwiftUI

@Observable
public final class DashboardViewModel {
    public var service = SpacetimeService.shared
    
    public static let defaultPaymentMethods = [
        "Bank Transfer",
        "Cash",
        "Credit Card",
        "Debit Card",
        "E-Wallet",
        "Apple Pay"
    ]
    
    // Data State
    public var userProfile: UserProfileItem?
    public var needsOnboarding: Bool = false
    public var accounts: [AccountItem] = AccountItem.defaultAccounts
    public var activeAccountId: String = "acc-personal"
    public var categories: [CategoryItem] = []
    public var expenses: [ExpenseItem] = []
    public var isLoading: Bool = false
    public var errorMessage: String?
    
    // Filtering & Preferences
    public var selectedPeriod: FilterPeriod = .thisWeek
    public var selectedFilterCategoryId: UInt64? = nil
    public var selectedPaymentMethod: String? = nil
    public var searchQuery: String = ""
    public var currency: CurrencyItem = CurrencyItem.defaultCurrency
    public var startWeekOn: String = "Sunday" // "Sunday" or "Monday"
    public var smartSuggestionsEnabled: Bool = true
    
    // Undo soft-deletion state
    public var lastDeletedExpense: ExpenseItem?
    public var showingUndoBar: Bool = false
    private var undoTimer: Timer?
    
    public init() {}
    
    public var activeAccount: AccountItem {
        accounts.first(where: { $0.id == activeAccountId }) ?? accounts.first ?? AccountItem.defaultAccounts[0]
    }
    
    public func categoryFor(id: UInt64) -> CategoryItem? {
        categories.first(where: { $0.id == id })
    }
    
    // Filtered expenses for active account
    public var accountExpenses: [ExpenseItem] {
        expenses.filter { exp in
            (exp.accountId ?? "acc-personal") == activeAccountId
        }
    }
    
    // MARK: - Payday Cycle & Spending Telemetry Engine
    public var currentPaydayCycle: PaydayCycle {
        let day = userProfile?.billingCycleStartDay ?? 1
        return PaydayCycle.current(billingCycleStartDay: day)
    }
    
    /// Pure domain spending telemetry snapshot generated by the SpendingTelemetryEngine
    public var telemetry: SpendingTelemetrySnapshot {
        SpendingTelemetryEngine.analyze(
            expenses: baseFilteredExpenses,
            categories: categories,
            paydayCycle: currentPaydayCycle,
            period: selectedPeriod,
            currency: currency,
            startWeekOn: startWeekOn
        )
    }
    
    // Pass-through computed properties for SwiftUI presentation layer
    public var cycleExpenses: [ExpenseItem] {
        let cycle = currentPaydayCycle
        return accountExpenses.filter { cycle.contains(date: $0.spentDate) }
    }
    
    public var envelopeStatuses: [CategoryEnvelopeStatus] {
        telemetry.envelopes.statuses
    }
    
    public var cycleTotalSpentCents: Int64 {
        telemetry.pace.cycleTotalSpentCents
    }
    
    public var cycleTotalBudgetCents: Int64 {
        telemetry.pace.cycleTotalBudgetCents
    }
    
    public var overspentEnvelopeCount: Int {
        telemetry.envelopes.overspentCount
    }
    
    public var cycleTotalDays: Int {
        telemetry.pace.totalDays
    }
    
    public var cycleCurrentDayIndex: Int {
        telemetry.pace.currentDayIndex
    }
    
    public var dailyBudgetAllowanceCents: Int64 {
        telemetry.pace.dailyBudgetAllowanceCents
    }
    
    public var freeToSpendCents: Int64 {
        telemetry.pace.freeToSpendCents
    }
    
    public var idealPaceSpendToDateCents: Int64 {
        telemetry.pace.idealPaceSpendToDateCents
    }
    
    public var isCyclePacingAhead: Bool {
        telemetry.pace.isCyclePacingAhead
    }
    
    public var cyclePaceDeltaCents: Int64 {
        telemetry.pace.cyclePaceDeltaCents
    }
    
    public var cyclePaceStatusText: String {
        telemetry.pace.statusText
    }
    
    public var cyclePacePoints: [CyclePacePoint] {
        telemetry.pace.pacePoints
    }
    
    public var isFilterActive: Bool {
        selectedFilterCategoryId != nil || (selectedPaymentMethod != nil && selectedPaymentMethod != "All") || selectedPeriod != .thisWeek
    }
    
    public var activeFilterDescription: String {
        var parts: [String] = []
        if selectedPeriod != .thisWeek {
            parts.append(selectedPeriod.title)
        }
        if let catId = selectedFilterCategoryId, let cat = categoryFor(id: catId) {
            parts.append(cat.name)
        }
        if let method = selectedPaymentMethod, method != "All" {
            parts.append(method)
        }
        return parts.joined(separator: ", ")
    }
    
    public func clearAllFilters() {
        selectedFilterCategoryId = nil
        selectedPaymentMethod = nil
        selectedPeriod = .thisWeek
    }

    public var periodTitle: String {
        telemetry.distribution.periodTitle
    }
    
    // Base expenses filtered by active account, search query, category, and payment method
    public var baseFilteredExpenses: [ExpenseItem] {
        var filtered = accountExpenses
        
        if !searchQuery.trimmingCharacters(in: .whitespaces).isEmpty {
            let q = searchQuery.lowercased()
            filtered = filtered.filter { exp in
                let catName = categoryFor(id: exp.categoryId)?.name.lowercased() ?? ""
                return exp.note.lowercased().contains(q) || catName.contains(q) || String(exp.amountCents).contains(q)
            }
        }
        
        if let catId = selectedFilterCategoryId {
            filtered = filtered.filter { $0.categoryId == catId }
        }
        
        if let method = selectedPaymentMethod, !method.isEmpty, method != "All" {
            filtered = filtered.filter { exp in
                exp.paymentMethod.localizedCaseInsensitiveContains(method) ||
                method.localizedCaseInsensitiveContains(exp.paymentMethod)
            }
        }
        
        return filtered
    }
    
    // Expenses matching all active filters including period
    public var filteredExpenses: [ExpenseItem] {
        let calendar = Calendar.current
        let now = Date()
        let filtered = baseFilteredExpenses
        
        switch selectedPeriod {
        case .today:
            return filtered.filter { calendar.isDateInToday($0.spentDate) }
        case .thisWeek:
            guard let weekInterval = calendar.dateInterval(of: .weekOfYear, for: now) else { return filtered }
            return filtered.filter { $0.spentDate >= weekInterval.start && $0.spentDate < weekInterval.end }
        case .thisMonth:
            guard let monthInterval = calendar.dateInterval(of: .month, for: now) else { return filtered }
            return filtered.filter { $0.spentDate >= monthInterval.start && $0.spentDate < monthInterval.end }
        case .thisYear:
            guard let yearInterval = calendar.dateInterval(of: .year, for: now) else { return filtered }
            return filtered.filter { $0.spentDate >= yearInterval.start && $0.spentDate < yearInterval.end }
        case .allTime:
            return filtered
        }
    }
    
    // Total spent for the selected period
    public var periodTotalCents: Int64 {
        telemetry.distribution.periodTotalCents
    }
    
    public var weeklyTotalCents: Int64 {
        periodTotalCents
    }
    
    // Dynamic Chart Data based on selectedPeriod
    public var chartData: [DaySpending] {
        telemetry.distribution.chartData
    }
    
    public var chartDataWithCategories: [DaySpendingWithCategories] {
        telemetry.distribution.categorizedChartData
    }
    
    public var weeklyChartData: [DaySpending] {
        chartData
    }
    
    // Grouped expenses by Day Name / Date
    public var groupedExpenses: [(key: String, expenses: [ExpenseItem])] {
        let filtered = filteredExpenses
        
        let formatter = DateFormatter()
        formatter.dateFormat = "EEEE, d MMM"
        
        let groups = Dictionary(grouping: filtered) { exp in
            let date = exp.spentDate
            let cal = Calendar.current
            if cal.isDateInToday(date) {
                return "Today"
            } else if cal.isDateInYesterday(date) {
                return "Yesterday"
            } else {
                return formatter.string(from: date)
            }
        }
        
        // Sort groups with recent dates first
        return groups.map { (key: $0.key, expenses: $0.value.sorted(by: { $0.spentAtMillis > $1.spentAtMillis })) }
            .sorted { g1, g2 in
                guard let first1 = g1.expenses.first, let first2 = g2.expenses.first else { return false }
                return first1.spentAtMillis > first2.spentAtMillis
            }
    }

    
    // MARK: - Data Actions
    
    public func refreshAll() async {
        isLoading = true
        await loadUserProfile()
        await loadCategories()
        await loadExpenses()
        isLoading = false
    }

    public func loadUserProfile() async {
        do {
            if let profile = try await service.fetchUserProfile() {
                self.userProfile = profile
                self.needsOnboarding = false
            } else {
                self.userProfile = nil
                self.needsOnboarding = true
            }
        } catch {
            print("DashboardViewModel: Failed to fetch user profile: \(error)")
        }
    }
    
    public func loadCategories() async {
        do {
            let fetched = try await service.fetchCategories()
            self.categories = fetched
        } catch {
            print("DashboardViewModel: Failed to load categories: \(error)")
        }
    }
    
    public func syncTelemetryToSharedStore() {
        let weeklySnapshot = SpendingTelemetryEngine.analyze(
            expenses: baseFilteredExpenses,
            categories: categories,
            paydayCycle: currentPaydayCycle,
            period: .thisWeek,
            currency: currency,
            startWeekOn: startWeekOn
        )
        SharedTelemetryStore.shared.save(snapshot: weeklySnapshot, currency: currency)
    }
    
    public func loadExpenses() async {
        do {
            let fetched = try await service.fetchRecentExpenses()
            self.expenses = fetched
            syncTelemetryToSharedStore()
        } catch {
            print("DashboardViewModel: Failed to load expenses: \(error)")
        }
    }
    
    public func deleteExpense(_ item: ExpenseItem) {
        Haptics.notification(.warning)
        withAnimation(.spring(response: 0.35, dampingFraction: 0.8)) {
            expenses.removeAll(where: { $0.id == item.id })
            lastDeletedExpense = item
            showingUndoBar = true
        }
        
        undoTimer?.invalidate()
        undoTimer = Timer.scheduledTimer(withTimeInterval: 5.0, repeats: false) { [weak self] _ in
            withAnimation(.spring(response: 0.3, dampingFraction: 0.8)) {
                self?.showingUndoBar = false
                self?.lastDeletedExpense = nil
            }
        }
        
        Task {
            do {
                try await service.softDeleteExpense(expenseId: item.id)
            } catch {
                print("Failed to soft delete: \(error)")
                await loadExpenses()
            }
        }
    }
    
    public func undoDelete(_ item: ExpenseItem) {
        undoTimer?.invalidate()
        Haptics.notification(.success)
        
        withAnimation(.spring(response: 0.35, dampingFraction: 0.8)) {
            showingUndoBar = false
            if !expenses.contains(where: { $0.id == item.id }) {
                expenses.append(item)
                expenses.sort(by: { $0.spentAtMillis > $1.spentAtMillis })
            }
        }
        
        Task {
            do {
                try await service.restoreExpense(expenseId: item.id)
                await loadExpenses()
            } catch {
                print("Failed to restore: \(error)")
            }
        }
    }
    
    public func addAccount(name: String) {
        guard !name.trimmingCharacters(in: .whitespaces).isEmpty else { return }
        let newAcc = AccountItem(
            id: "acc-\(UUID().uuidString.prefix(8))",
            name: name.trimmingCharacters(in: .whitespaces),
            icon: "briefcase.fill",
            balanceCents: 0,
            isDefault: false
        )
        accounts.append(newAcc)
        activeAccountId = newAcc.id
    }
    
    public func deleteAccount(id: String) {
        guard accounts.count > 1 else { return }
        accounts.removeAll(where: { $0.id == id })
        if activeAccountId == id {
            activeAccountId = accounts.first?.id ?? "acc-personal"
        }
    }
}
